build(www): install step

diff --git a/www/moon.yml b/www/moon.yml
--- a/www/moon.yml
+++ b/www/moon.yml
@@ -8,7 +8,13 @@ project:
 tasks:
   install:
     description: Install dependencies
-    command: bun install
+    script: |
+      if ! command -v bun &> /dev/null; then
+        echo "Bun not found, installing..."
+        curl -fsSL https://bun.sh/install | bash
+      end
+
+      bun install
 
   build:
     description: Build the website
@@ -18,6 +24,7 @@ tasks:
       - "public/**/*"
     outputs:
       - "dist"
+
   dev:
     description: Start the development server
     command: bun run dev
